[build]
  command = "npm run build:netlify"
  publish = ".next"

# Use the Next.js Runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Copy the database file during build
[[plugins]]
  package = "./plugins/netlify-plugin-copy-files"
  
  [plugins.inputs]
  source = "db/portfolio.db"
  destination = ".next/server/db/portfolio.db"

# Copy the WAL file during build
[[plugins]]
  package = "./plugins/netlify-plugin-copy-files"
  
  [plugins.inputs]
  source = "db/portfolio.db-wal"
  destination = ".next/server/db/portfolio.db-wal"

# Copy the SHM file during build
[[plugins]]
  package = "./plugins/netlify-plugin-copy-files"
  
  [plugins.inputs]
  source = "db/portfolio.db-shm"
  destination = ".next/server/db/portfolio.db-shm"

# Environment variables
[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Cache control headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), microphone=()" 