# Simple Netlify Configuration for Next.js
[build]
  command = "npm install autoprefixer postcss tailwindcss @netlify/plugin-nextjs --no-save && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Production environment
[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# SPA Fallback redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 