[build]
  command = "npm run build"
  publish = ".next"

# Use the Next.js Runtime with SQLite file handling
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [plugins.inputs]
    # Copy the SQLite database to the publish directory
    includeFiles = ["*.db", "database.sqlite", "*.sqlite"]

# Environment variables
[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "true"

# Cache control headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), microphone=()"

[functions]
  # Increase function timeout for database operations
  node_bundler = "esbuild"
  external_node_modules = ["better-sqlite3"]