[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

# Netlify Edge Functions
[[edge_functions]]
  function = "api/*"
  path = "/api/*"

# Headers to prevent caching of API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

# Redirects for Next.js API routes and dynamic routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 