[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--no-optional"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["better-sqlite3", "sharp"]

# Headers to prevent caching of API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    X-Custom-Header = "Make sure this works"

# Force rebuild and ignore build cache
[build.processing]
  skip_processing = false

# Handle Next.js routes
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-api/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.lifecycle]
  onPreBuild = "node netlify-preinstall.js" 