[phases.setup]
nixPkgs = ['nodejs-18_x', 'sqlite']
nodeVersion = "18.x"

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[phases.start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production' 